### ISSUE TITLE
Forked for addition of a Skills taxonomy

### ISSUE THREAD

**Issue by VictorBargains** [benbalter/WP-Resume#26]
Hi. I love your plugin and wanted to make an enhancement to it for my web site so it could display Skills used on each of my Positions. I forked master (cause develop seemed to be behind) and tried following the conventions used for the `wp_resume_organization` and `wp_resume_section` taxonomies, and with a little bit of quick CSS I think I got it looking at least good enough for a rough draft.

https://github.com/VictorBargains/WP-Resume

I've added a `wp_resume_skill` taxonomy, a custom ajax editor for it, nested skills displayed as skill groups enclosing individual skills, and skill levels displayed as thin progress bars. I added options for enabling both skills and skill groups, so by default nobody's resume appearance should change, even if they added skill terms to the taxonomy. With these options it's possible to get a linear list of skills without grouping by enabling skills but not groups.

I'm sure there are a few things I missed, or didn't do quite right, but the feature works fairly well as far as I can tell from my own testing. I'm still in the process of integrating it into my own website and working with my own hierarchy of skills and custom templates to display the data optimally. 

I'd love a code review, and some help in spotting what's missing to make it ready for integrating it with the main repo, if that's something anyone would want. In the meantime, I'm tracking my own list of improvements I think need to be made to the Skills feature. If you spot something, feel free to add an issue:

https://github.com/VictorBargains/WP-Resume/issues

I'd be open to collaboration on expanding this feature, as well as possible development of additional features such as Project as a custom post type which can have a Position as a parent and Skills as a taxonomy relationship.

---

Here are some screenshots. First, of the skills panel added to the edit page for positions:
![screen shot 2016-09-07 at 2 39 11 pm](https://cloud.githubusercontent.com/assets/2579047/18329587/130ea1ae-7509-11e6-9a4b-8889080c49e0.png)

This is an example of what the default styling of the skills looks like. There are a few visual hiccups, notably the skill level bar for C# appearing above the text instead of below, but it's not a bad start.
![screen shot 2016-09-07 at 2 36 51 pm](https://cloud.githubusercontent.com/assets/2579047/18329601/2f209636-7509-11e6-819a-2708550036db.png)

Here is a custom style sheet I'm using on my own site which colors the skill groups by name:
![screen shot 2016-09-07 at 2 33 43 pm](https://cloud.githubusercontent.com/assets/2579047/18329442/40b3ea84-7508-11e6-9967-9f0037c29f57.png)

And here is an example of that custom CSS, based on the slugs I gave my skills in my data:

```
.resume li.skill-group-web-development { background-color:#009966; }
.resume li.skill-group-graphic-design-and-print { background-color:#939; }
.resume li.skill-group-systems-administration { background-color:#782F50; }
.resume li.skill-group-programming-languages { background-color:#FC0; }
.resume li.skill-group-computer-and-it-support { background-color:#8E78B6; }
.resume li.skill-group-soft-skills { background-color:#09C; }
```

**Comment by benbalter** [comment]
@VictorBargains Thanks for this. If you'd be willing to maintain it, I'd be glad to merge these changes if you can put a pull request together.

**Comment by VictorBargains** [comment]
I'm gonna fix a few of the obvious bugs first, but I will make a pull request when I think it's ready.

**Comment by benbalter** [comment]
Awesome. Thanks @VictorBargains!
